name: Deno

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        run: pwd | curl -fsSL https://deno.land/x/install/install.sh | export DENO_INSTALL="/home" | export PATH="$DENO_INSTALL/bin:$PATH"

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A 
